#! /bin/bash

# heavily inspired from athakur
# touch .gitignore # copied from github
# touch LICENSE
# -d to init a new repo 

if [ -d ./src ]; then rm -rf src; fi
if [ -d ./data ]; then rm -rf data; fi
if [ -d ./models ]; then rm -rf models; fi
if [ -d ./config ]; then rm -rf config; fi

export d=$1
export uid=$2
export repo=$3

mkdir src data models config
cd src/
touch utils.py train.py metrics.py loss.py 
touch get_preds.py get_data.py
cd -
touch config/env.yml

echo ":done, add data/ models/ to .gitignore if needed"
if [ "${d:1:10}" == "d" ]
  then 
  	echo ":got option -d"
    rm -rf .git
    echo "## ${repo} " > README.md
    git init .
    echo ":reinitialised new git, no HEAD"
    git add README.md
    git commit -m "first commit"
    git branch -M main
    git remote add origin git@github.com:${uid}/${repo}.git
    git push -u origin main
  fi

